// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: rpcgo/rpcgo.proto

package rpcgo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DoStuffClient is the client API for DoStuff service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DoStuffClient interface {
	PrintHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type doStuffClient struct {
	cc grpc.ClientConnInterface
}

func NewDoStuffClient(cc grpc.ClientConnInterface) DoStuffClient {
	return &doStuffClient{cc}
}

func (c *doStuffClient) PrintHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/rpcgo.DoStuff/PrintHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DoStuffServer is the server API for DoStuff service.
// All implementations must embed UnimplementedDoStuffServer
// for forward compatibility
type DoStuffServer interface {
	PrintHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedDoStuffServer()
}

// UnimplementedDoStuffServer must be embedded to have forward compatible implementations.
type UnimplementedDoStuffServer struct {
}

func (UnimplementedDoStuffServer) PrintHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintHello not implemented")
}
func (UnimplementedDoStuffServer) mustEmbedUnimplementedDoStuffServer() {}

// UnsafeDoStuffServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DoStuffServer will
// result in compilation errors.
type UnsafeDoStuffServer interface {
	mustEmbedUnimplementedDoStuffServer()
}

func RegisterDoStuffServer(s grpc.ServiceRegistrar, srv DoStuffServer) {
	s.RegisterService(&DoStuff_ServiceDesc, srv)
}

func _DoStuff_PrintHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoStuffServer).PrintHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcgo.DoStuff/PrintHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoStuffServer).PrintHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DoStuff_ServiceDesc is the grpc.ServiceDesc for DoStuff service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DoStuff_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpcgo.DoStuff",
	HandlerType: (*DoStuffServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrintHello",
			Handler:    _DoStuff_PrintHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcgo/rpcgo.proto",
}
